---
openapi: '3.0.3'
info:
  version: 1.0.1
  title: Example
paths:
  /test1:
    summary: Path summary
    description: Path description
    get:
      operationId: getTest1
      summary: Operation summary
      responses:
        200:
          description: OK
    post:
      operationId: postTest1
      description: Operation description
      parameters:
        - name: a
          in: query
          schema:
            type: string
      responses:
        200:
          description: OK
