---
openapi: '3.0.3'
info:
  version: 1.0.1
  title: Example
paths:
  /test1:
    parameters:
      - name: b
        in: query
        schema:
          type: string
    get:
      operationId: getTest1
      responses:
        200:
          description: OK
    post:
      operationId: postTest1
      parameters:
        - name: a
          in: query
          schema:
            type: string
      responses:
        200:
          description: OK
